<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFPplWYy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFPplWYy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFPplWYy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFPplWYy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFPplWYy\App_KernelDevDebugContainer([
    'container.build_hash' => 'FPplWYy',
    'container.build_id' => '7e284143',
    'container.build_time' => 1576499836,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFPplWYy');
