<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFoUvlxE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFoUvlxE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFoUvlxE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFoUvlxE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFoUvlxE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FoUvlxE',
    'container.build_id' => 'b27ccb23',
    'container.build_time' => 1576499081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFoUvlxE');
